### ISSUE TITLE
Lidatube downloading songs not found in Lidarr 

### ISSUE THREAD

**Issue by MARAllMighty** [TheWicklowWolf/LidaTube#1]
I ran this tool recently on the first 250 results and was pleased with what was found. However, when I go to import into Lidarr, many of the tracks downloaded are not found in Lidarr and cannot be imported. 

Do you know why that might be?

**Comment by TheWicklowWolf** [comment]
The issue likely arises from the limited availability of comprehensive metadata on YouTube. The tool may struggle to extract sufficient information, impacting the accurate import of tracks into Lidarr.
I have an idea on how to add more metadata but I haven't implemented it yet.

To try Import them into Lidarr, you can try: Library-> Unmapped Files -> Add missing.
If that doesn't pick them up, you will probably have to add them manually (once per each unmapped album)

**Comment by TheWicklowWolf** [comment]
New version out, which should add more metadata and make it easier for Lidarr to match albums
