### ISSUE TITLE
Tag Artifacts with Semver

### ISSUE THREAD

**Issue by ionfury** [TheWicklowWolf/LidaTube#10]
Hello,

Trying out your app and I really like it!  It would be very helpful if you tagged releases according to [semver standards](https://semver.org/), specifically to be compatible with dependency automation tools like [renovate](https://github.com/renovatebot/renovate) or [flux](https://fluxcd.io/flux/guides/image-update/).  Additionally, if you could include these tags in the [dockerhub images] published from here, that would be great!

**Comment by TheWicklowWolf** [comment]
Out of scope as only using :latest tag for simplicity
