### ISSUE TITLE
Lidarr API sortKey does not work with external Postgres backend

### ISSUE THREAD

**Issue by ionfury** [TheWicklowWolf/LidaTube#11]
[Reference Issue in lidar](https://github.com/Lidarr/Lidarr/issues/3392)

Trying out lidarr requests:

```curl --location 'https://{lidarr}/api/v1/wanted/missing?includeArtist=true&apikey={key}&sortKey=artists.sortname&sortDirection=ascending'```

```...
Exception data:\n    Severity: ERROR\n    SqlState: 42703\n    MessageText: column \"Sortname\" does not exist\n    Hint: Perhaps you meant to reference the column \"Artists.SortName\".\n    Position: 536\n    File: parse_relation.c\n    Line: 3656\n    Routine: errorMissingColumn"
```

```curl --location 'https://{lidarr}/api/v1/wanted/missing?includeArtist=true&apikey={key}&sortKey=artists.sortName&sortDirection=ascending'```

```...
Exception data:\n    Severity: ERROR\n    SqlState: 42803\n    MessageText: column \"Artists.SortName\" must appear in the GROUP BY clause or be used in an aggregate function\n    Position: 536\n    File: parse_agg.c\n    Line: 1433\n    Routine: check_ungrouped_columns_walker"
```
Would it be possible to disable sorting until the above lidarr issue is resolved?

**Comment by TheWicklowWolf** [comment]
Only Lidarr standard form is supported, you'll have to fork it to suit.

**Comment by TheWicklowWolf** [comment]
I've removed sortKey and sortDirection as the sorting is now done after the API call. So this should resolve your issue.

**Comment by ionfury** [comment]
Great, thanks!
