### ISSUE TITLE
Prevent IP Blocking by YouTube

### ISSUE THREAD

**Issue by NovaCyntax** [TheWicklowWolf/LidaTube#15]
Ran this on a large collection upon first install, and was hit with a block. I now receive the "Your IP is likely being blocked by YouTube" errors, with a number of 500 after letting it run through my collection.

Apart from using sleep scheduling (which I didn't), perhaps consider allowing changing between IPV4 and IPV6 addresses, which I believe are flags that can be passed via yt-dlp. Swapping between public IPV4 and IPV6 addresses is one way to get around rate-limited (or similar) bans. 

I believe this would be as simple as the introduction of an environment variable, such as "`force_ip_type`", with the configuration options of "`ipv4`" and "`ipv6`". The "`ipv4`" option would pass the "`--force-ipv4`" option to yt-dlp, and the "`ipv6`" option would pass the "`--force-ipv6`" option. I believe that these options can be shortened to "`-4`" and "`-6`" respectively.

Another potential option may be openvpn integration if you wanted to be overkill.

**Comment by TheWicklowWolf** [comment]
While this implementation is straightforward, it's unlikely to work in this instance based on my understanding, as most people set up their containers to operate on IPv4 (and LidaTube only binds to IPv4 addresses). Therefore, attempting to force IPv6 from within the container probably won't be successful and may potentially revert to IPv4 as a fallback. I'm open to any corrections on that.

Alternatively, using cookies might be a viable option. This would involve obtaining a cookies.txt file from a non-rate-limited machine/address and utilizing it in yt-dlp.

```If a cookies.txt file exists in the config folder, use that path in yt-dlp. ```
```Conversely, if the cookies.txt file is not present, don't use any cookie file.```
