### ISSUE TITLE
Write Metadata to Tracks Using Beets (or similar)

### ISSUE THREAD

**Issue by NovaCyntax** [TheWicklowWolf/LidaTube#16]
Upon running on a large media collection, the songs that were downloaded had the incorrect album art embedded in the tracks (they were the YouTube thumbnails instead). The album art in my music players would be correct, but upon pressing on a song, the album art displayed would be the YouTube thumbnail.

This is because (to my understanding) Lidarr does not write album art images to music files, or something similar. Upon importing all new songs to Lidarr (and scanning and replacing all metadata within Lidarr), the incorrect album art images persisted within the track files.

Regardless of the root cause, I had to run my entire library through MusicBrainz Picard in order to write the correct album art images to each track downloaded from LidaTube - which took many, many hours. This process could be potentially automated by having LidaTube run each downloaded file into Beets (or similar) upon completing a download.

**Comment by TheWicklowWolf** [comment]
Integrating Beets or similar tools into LidaTube duplicates functions already provided by Lidarr. Therefore, implementing this solution is currently out of scope.
Also it seems you've already found a method to address this issue. 

Open PRs if this feature is important to you.
