### ISSUE TITLE
More info on what exactly this does...

### ISSUE THREAD

**Issue by bonelifer** [TheWicklowWolf/LidaTube#18]
More information on what exactly this does and how it integrates with Lidarr.

**Comment by TheWicklowWolf** [comment]
What... "Web GUI for finding and downloading missing Lidarr albums." doesn't cover it?
How about "It reads the missing album list from Lidarr, searches for a corresponding match on YT, and retrieves the album/missing tracks using yt-dlp."

**Comment by TheWicklowWolf** [comment]
Unfortunately proper documentation costs extra.

**Comment by bonelifer** [comment]
So we'd just make this a Root so it scans in, is what I was asking.
```
      - /data/media/lidatube:/lidatube/downloads
```
