### ISSUE TITLE
Feature Request: Set folder structure and files names for downloads

### ISSUE THREAD

**Issue by dnick5000** [TheWicklowWolf/LidaTube#19]
Hi, I was wondering if it would be possible to set the file names and folder structure/names for downloaded files. That way, it would be possible to use the Usenet blackhole feature of Lidarr to import from the LidaTube downloads folder. Right now, Lidarr cannot see each album, as each album ends up nested in a folder with the artist name. Ideally, I'd like LidaTube to name each downloaded album as Artist - Album (year)/01 - track 1.mp3 etc.

**Comment by TheWicklowWolf** [comment]
The current folder/filename structure is set to match the default Lidarr structure, which allows you to map the LidaTube download folder directly into your music folder. 

Unfortunately I have no desire to make this configurable as I don't see a use case for it.
