### ISSUE TITLE
Sort Order

### ISSUE THREAD

**Issue by samcro1967** [TheWicklowWolf/LidaTube#2]
I believe the following code:

```
 params = {"apikey": self.lidarrApiKey, "pageSize": self.lidarrMaxTags, "sortKey": "artists.sortname", "sortDir": "asc"}
```

Should be as follows:
```
 params = {"apikey": self.lidarrApiKey, "pageSize": self.lidarrMaxTags, "sortKey": "artists.sortname", "sortDirection": "ascending"}
```

If I am reading the API documentation correctly...
https://lidarr.audio/docs/api/#/Missing/get_api_v1_wanted_missing

**Comment by samcro1967** [comment]
The same update probably also applies to BookBounty.  Thanks for the quick fix.

**Comment by TheWicklowWolf** [comment]
BookBounty updated, thanks again
