### ISSUE TITLE
Search filters

### ISSUE THREAD

**Issue by TheDestr0yer** [TheWicklowWolf/LidaTube#20]
Hi first of all congratulations for this project ,really very useful ,it would be even more interesting if in the future there would be the possibility to set filters ,for example I noticed that sometimes live tracks are downloaded.

**Comment by TheWicklowWolf** [comment]
Thank you for your suggestion..
 
In Lidarr, there is an option to change the album release type to one that doesn't include live tracks. You can do this by deselecting "Automatically Switch Release" for the album and then choosing a Digital Release or CD, for example. 

Additionally, you can set the Minimum Match Ratio to 100% to ensure it only downloads exact matches.
