### ISSUE TITLE
Not downloading anything.

### ISSUE THREAD

**Issue by neilanthonystuckey** [TheWicklowWolf/LidaTube#22]
It looks like its trying to download from youtube but nothing in the download folder and it goes really fast maybe a second or two then says download complete. 

services:
  lidatube:
    image: thewicklowwolf/lidatube:latest
    container_name: lidatube
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/lidarr2/config:/lidatube/config:rw
      - /mnt/wd4tb/downloads/complete/lidatube:/lidatube/downloads:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5055:5000
    restart: unless-stopped

I was able to pull this info from lidatube logs from portainer 

Not matching album for: Frank Zappa - Whisky a Go Go, 1968
Links found for all tracks of: Frank Zappa - Whisky a Go Go, 1968
Searching for Album: U2 - Atomic City (Tiësto remix)
Searching for whole Album: U2 - Atomic City (Tiësto remix)
Not matching album for: U2 - Atomic City (Tiësto remix)
Links found for all tracks of: U2 - Atomic City (Tiësto remix)
Searching for Album: Within Temptation - Worlds Collide Tour (Live in Amsterdam)
Searching for whole Album: Within Temptation - Worlds Collide Tour (Live in Amsterdam)
Not matching album for: Within Temptation - Worlds Collide Tour (Live in Amsterdam)
Links found for all tracks of: Within Temptation - Worlds Collide Tour (Live in Amsterdam)
Searching for Album: Dark Funeral - Shadows Over Transylvania
Searching for whole Album: Dark Funeral - Shadows Over Transylvania
Not matching album for: Dark Funeral - Shadows Over Transylvania
Links found for all tracks of: Dark Funeral - Shadows Over Transylvania
Searching for Album: Bob Dylan - Smoking Down the Track- I and I - 1984-1999
Searching for whole Album: Bob Dylan - Smoking Down the Track- I and I - 1984-1999
Not matching album for: Bob Dylan - Smoking Down the Track- I and I - 1984-1999
Links found for all tracks of: Bob Dylan - Smoking Down the Track- I and I - 1984-1999
Searching for Album: Orange Goblin - The Fire At The Centre Of The Earth Is Mine
Searching for whole Album: Orange Goblin - The Fire At The Centre Of The Earth Is Mine
Not matching album for: Orange Goblin - The Fire At The Centre Of The Earth Is Mine
Links found for all tracks of: Orange Goblin - The Fire At The Centre Of The Earth Is Mine
Searching for Album: Boris - ANOTHER NOISE
Searching for whole Album: Boris - ANOTHER NOISE
Not matching album for: Boris - ANOTHER NOISE
Links found for all tracks of: Boris - ANOTHER NOISE
Searching for Album: The Japanese House - -)
Searching for whole Album: The Japanese House - -)
Not matching album for: The Japanese House - -)
Links found for all tracks of: The Japanese House - -)
Searching for Album: David Gilmour - Between Two Points
Searching for whole Album: David Gilmour - Between Two Points
Not matching album for: David Gilmour - Between Two Points
Links found for all tracks of: David Gilmour - Between Two Points
Searching for Album: Melvins - Twins of Evil
Searching for whole Album: Melvins - Twins of Evil
Not matching album for: Melvins - Twins of Evil
Links found for all tracks of: Melvins - Twins of Evil
Searching for Album: Fleshgod Apocalypse - Bloodclock
Searching for whole Album: Fleshgod Apocalypse - Bloodclock
Not matching album for: Fleshgod Apocalypse - Bloodclock
Links found for all tracks of: Fleshgod Apocalypse - Bloodclock
Searching for Album: Sam Feldt - Mi Amor
Searching for whole Album: Sam Feldt - Mi Amor
Not matching album for: Sam Feldt - Mi Amor
Links found for all tracks of: Sam Feldt - Mi Amor
Searching for Album: The Decemberists - As It Ever Was, So It Will Be Again
Searching for whole Album: The Decemberists - As It Ever Was, So It Will Be Again
Not matching album for: The Decemberists - As It Ever Was, So It Will Be Again
Links found for all tracks of: The Decemberists - As It Ever Was, So It Will Be Again
Searching for Album: R.E.M. - R.E.M.’s Top Forty Playlist (according to Berry, Buck, Mills and Stipe)
Searching for whole Album: R.E.M. - R.E.M.’s Top Forty Playlist (according to Berry, Buck, Mills and Stipe)
Not matching album for: R.E.M. - R.E.M.’s Top Forty Playlist (according to Berry, Buck, Mills and Stipe)
Links found for all tracks of: R.E.M. - R.E.M.’s Top Forty Playlist (according to Berry, Buck, Mills and Stipe)
Searching for Album: The Saints - Break Away
Searching for whole Album: The Saints - Break Away
Not matching album for: The Saints - Break Away
Links found for all tracks of: The Saints - Break Away
Searching for Album: Van Halen - Top of the World (live at the West End Marketplace, Dallas, Tx, 12+4+1991)
Searching for whole Album: Van Halen - Top of the World (live at the West End Marketplace, Dallas, Tx, 12+4+1991)
Not matching album for: Van Halen - Top of the World (live at the West End Marketplace, Dallas, Tx, 12+4+1991)
Links found for all tracks of: Van Halen - Top of the World (live at the West End Marketplace, Dallas, Tx, 12+4+1991)
Searching for Album: IDLES - Spotify Singles
Searching for whole Album: IDLES - Spotify Singles
Not matching album for: IDLES - Spotify Singles
Links found for all tracks of: IDLES - Spotify Singles
Searching for Album: Toro y Moi - Tuesday
Searching for whole Album: Toro y Moi - Tuesday
Not matching album for: Toro y Moi - Tuesday
Links found for all tracks of: Toro y Moi - Tuesday
Searching for Album: Pearl Jam - 2024-05-25- BottleRock, Napa Valley Expo, Napa, CA, USA
Searching for whole Album: Pearl Jam - 2024-05-25- BottleRock, Napa Valley Expo, Napa, CA, USA
Not matching album for: Pearl Jam - 2024-05-25- BottleRock, Napa Valley Expo, Napa, CA, USA
Links found for all tracks of: Pearl Jam - 2024-05-25- BottleRock, Napa Valley Expo, Napa, CA, USA
Searching for Album: Jethro Tull - Boston Tea Party, Boston 1970
Searching for whole Album: Jethro Tull - Boston Tea Party, Boston 1970
Not matching album for: Jethro Tull - Boston Tea Party, Boston 1970
Links found for all tracks of: Jethro Tull - Boston Tea Party, Boston 1970
Searching for Album: Johnny Cash - Spotlight + Well Alright
Searching for whole Album: Johnny Cash - Spotlight + Well Alright
Not matching album for: Johnny Cash - Spotlight + Well Alright
Links found for all tracks of: Johnny Cash - Spotlight + Well Alright
Searching for Album: Santana - Earthquake Relief Concert 1989
Searching for whole Album: Santana - Earthquake Relief Concert 1989
Not matching album for: Santana - Earthquake Relief Concert 1989
Links found for all tracks of: Santana - Earthquake Relief Concert 1989
Searching for Album: Testament - Into the Pit (2024 Remaster)
Searching for whole Album: Testament - Into the Pit (2024 Remaster)
Not matching album for: Testament - Into the Pit (2024 Remaster)
Links found for all tracks of: Testament - Into the Pit (2024 Remaster)
Searching for Album: The Offspring - Make It All Right
Searching for whole Album: The Offspring - Make It All Right
Not matching album for: The Offspring - Make It All Right
Links found for all tracks of: The Offspring - Make It All Right
Searching for Album: The Stooges - London Session 1972
Searching for whole Album: The Stooges - London Session 1972
Not matching album for: The Stooges - London Session 1972
Links found for all tracks of: The Stooges - London Session 1972
Downloading Finished
Lidarr library scan started

**Comment by neilanthonystuckey** [comment]
I have deleted the lidatube container folder and reinstalled it.  The api appears to be working with lidarr its finding missing albums.

**Comment by neilanthonystuckey** [comment]
Just for another test i installed lidarr bare metal as service and also on docker same issue.  Just goes through the motions but not downloading any files. 

bare metal lidarr as service
Version
    2.3.3.4204
Package Version
    2.3.3.4204-ls3 by [linuxserver.io](https://linuxserver.io/) 
.NET
    Yes (6.0.29)
Docker
    Yes
Database
    Sqlite 3.45.3
Database Migration
    78
AppData Directory
    /config
Startup Directory
    /app/lidarr/bin
Mode
    Console

docker lidarr
Version
    2.3.3.4204
.NET
    Yes (6.0.29)
Database
    Sqlite 3.46.0
Database Migration
    78
AppData Directory
    /mnt/dietpi_userdata/lidarr
Startup Directory
    /opt/lidarr
Mode
    Console

**Comment by TheWicklowWolf** [comment]
There is a new image with an updated version of yt-dp, you can get it using `docker compose pull && docker compose up -d`

See if that works..

**Comment by TheWicklowWolf** [comment]
Also make sure that user 1000:1000 has permission in your `/mnt/wd4tb/downloads/complete/lidatube` directory.

Side Note: I'd recommended Dozzle for viewing logs.

**Comment by neilanthonystuckey** [comment]
hmm same issue.. Thanks for the fast response.

**Comment by TheWicklowWolf** [comment]
That's weird... 

- Are you sure there is nothing else in the logs? As there doesn't seem to be any errors...
- Check your config file in `/opt/lidarr2/config` in case there is something strange in there
- And have you definitely pulled the latest image? (it was updated today)


You might have to run it locally to see what the issue is on your setup

**Comment by neilanthonystuckey** [comment]
I dont see any errors either and nothing in logs that show anything. Config file looks good to me. I docker exec'd into the container and set permissions there to all paths as well. 

 "lidarr_address": "http://192.168.2.136:8689",
    "lidarr_api_key": "myapi",
    "lidarr_api_timeout": 120.0,
    "thread_limit": 1,
    "sleep_interval": 0.0,
    "fallback_to_top_result": true,
    "library_scan_on_completion": true,
    "sync_schedule": [],
    "minimum_match_ratio": 90.0,
    "secondary_search": "YTS",
    "preferred_codec": "mp3",
    "attempt_lidarr_import": true

Are there any remnants on the system that would stay even if i delete the docker folder for the app ?

**Comment by TheWicklowWolf** [comment]
> Are there any remnants on the system that would stay even if i delete the docker folder for the app ?

No, there shouldn't be.. and you setup looks fine..
It's a strange one, there are no errors either and I can't replicate it....

There seems to be some issue running the code on your system.. you might have to clone the repo and run the python script to see exactly what's happening. 

Maybe check the Dozzle logs to see if they are more verbose..

**Comment by neilanthonystuckey** [comment]
Dozzle logs look the same nothing notable there.  How would i do this "There seems to be some issue running the code on your system.. you might have to clone the repo and run the python script to see exactly what's happening. "

**Comment by TheWicklowWolf** [comment]
Try setting `"fallback_to_top_result": false` and adjust your Minimum Match Ratio (%) as required on the UI. 
I would rarely use `fallback_to_top_result`  as the matching is not guaranteed and results can be wildly incorrect.

Also I've updated the image to add some more logging, try that with `docker compose pull && docker compose up -d` 
and see if that provides some more info.

**Comment by TheWicklowWolf** [comment]
Can't replicate
