### ISSUE TITLE
Lidarr import tuning parameter

### ISSUE THREAD

**Issue by TheLazyGeekGuy** [TheWicklowWolf/LidaTube#23]
> 2024-07-12 19:32:00.1|Debug|CloseAlbumMatchSpecification|Album match is not close enough: 0.42105263157894735 vs 0.2 [album, year, country]. Skipping [/lidatube/downloads/AHEE/Crystal Beam (2022)]
> 2024-07-12 19:32:00.1|Debug|ImportDecisionMaker|Album rejected for the following reasons: [Permanent] Album match is not close enough: 57.9% vs 80% [album, year, country]

I verified a couple of import with the right 3 parameters album, year, country, but the ratio match keep beeing low for lidarr import.

What do i need to increase the success import on album that are really the good ones ?

**Comment by TheWicklowWolf** [comment]
I haven't been able to find a reliable way to get imports to work consistently and I'm open to suggestions. 

I think the issue is due to factors like track length, file size, and differences in fingerprinting. These variations might be causing the match ratios to be lower than expected, even for the correct albums.

**Comment by TheLazyGeekGuy** [comment]
I've found the issue with lidarr debug, that came from the lack of reliability from the meta information that came from youtube.

I'm currently working of version your Lidatube.py that will overwrite meta information from youtube.
Actually that increase the success factor of import to lidarr, but i need to test more as there still on going issues.

I will keep you posted as it will be stable.

**Comment by TheWicklowWolf** [comment]
The correct metadata is already added to each file via `add_metadata` function in `_general.py`

If you want an easy way to improve import matching, you have the option to disable fingerprinting. 
However, this approach may _**potentially**_ lead to incorrect imports.

### **In Lidarr:**

- Settings -> Media Management -> Allow Fingerprinting -> Never 
(with advanced options shown)

**Comment by TheLazyGeekGuy** [comment]
> The correct metadata is already added to each file via `add_metadata` function in `_general.py`

But not for m4a ... which is my case ! :-)

> 
> If you want an easy way to improve import matching, you have the option to disable fingerprinting. However, this approach may _**potentially**_ lead to incorrect imports.
> ### **In Lidarr:**
> 
>     * Settings -> Media Management -> Allow Fingerprinting -> Never
>       (with advanced options shown)

Ok it seems i tried it.
