### ISSUE TITLE
Permissions and Post-Processing Errors

### ISSUE THREAD

**Issue by awkw4rdkid** [TheWicklowWolf/LidaTube#24]
Hi there. Found this in a Reddit thread and it's a super cool project. Running into some problems getting it going, though.

First thing is the general user (1000:1000) doesn't seem to have permissions for read/write in the downloads folder within the container itself. I was able to get around this using `docker exec -u root -it lidatube sh` and then running `chmod a+rwx downloads`. Download error itself seems to have gone away after that.

Still having issues with post-processing. The files download as .temp and never fully merge:

```
ERROR: Postprocessing: Error opening output files: Invalid argument
Error downloading song: https://www.youtube.com/watch?v=P2C2IhmP4gk. Error message: ERROR: Postprocessing: Error opening output files: Invalid argument
```

**Comment by TheWicklowWolf** [comment]
This sounds like a permission error. Ensure that user 1000:1000 has the necessary permissions for the directory you mounted to /lidatube/downloads.
For example, if you mapped `/data/media/music:/lidatube/downloads` make sure `/data/media/music` has 1000:1000 permissions on your host.

If you're still having issues, post your docker-compose.yml file, your configuration file (from wherever you mapped `/lidatube/config`), and the log file showing the sequence of events.
