### ISSUE TITLE
Sync schedule not accepting 24 hour time

### ISSUE THREAD

**Issue by hornofabraxas** [TheWicklowWolf/LidaTube#25]
First of all, thank you, this tool is great. I appreciate your work. 

I am trying to set up the sync schedule and I noticed: 

`08:35, 09:00, 10, 1130`

becomes: 

`0,10`

Whereas entering something like: 

`9,10,11,12`

Appears to save properly in the sync command, but does not appear to do anything on the hour like I would expect. 

I also tested this to see if it was expecting cronjob format and it didn't work as expected then either: 

`<minute> <hour> <day_of_month> <month> <day_of_week>`

**Comment by hornofabraxas** [comment]
Might be worth noting that: 

`- /etc/localtime:/etc/localtime:ro`

is listed under Volumes in my docker compose, and I confirmed the host system time is correct

**Comment by TheWicklowWolf** [comment]
For sync schedule use a comma-separated list of hours to search for albums/tracks (e.g., 2, 20 will initiate a search at 2 AM and 8 PM)

Note: It only checks every 10 minutes, and it sleeps for an hour after completing a sync.
