### ISSUE TITLE
Lidatube broken due to "poToken Experiments" Youtube rollout

### ISSUE THREAD

**Issue by hornofabraxas** [TheWicklowWolf/LidaTube#26]
Youtube is rolling out "poToken experiments" which breaks the version of yt-dlp that Lidatube is using, see Lidatube logs below:

```
WARNING: [youtube] Webpage contains broken formats **(poToken experiment detected)**. Ignoring initial player response
[youtube] NeoKe1LTWW0: Downloading ios player API JSON
[youtube] NeoKe1LTWW0: Downloading player 1f8742dc
[youtube] NeoKe1LTWW0: Downloading web player API JSON
WARNING: [youtube] NeoKe1LTWW0: nsig extraction failed: Some formats may be missing
         n = d6Qu9CfNhcKhglD48 ; player = https://www.youtube.com/s/player/1f8742dc/player_ias.vflset/en_US/base.js
WARNING: [youtube] NeoKe1LTWW0: nsig extraction failed: Some formats may be missing
         n = C0igT1mQ9xY3VB75K ; player = https://www.youtube.com/s/player/1f8742dc/player_ias.vflset/en_US/base.js
[youtube] NeoKe1LTWW0: Downloading m3u8 information
ERROR: [youtube] NeoKe1LTWW0: Requested format is not available. Use --list-formats for a list of available formats
Error downloading song: https://www.youtube.com/watch?v=NeoKe1LTWW0. Error message: ERROR: [youtube] NeoKe1LTWW0: **Requested format is not available.** Use --list-formats for a list of available formats
```
yt-dlp version 2024.07.16 has a fix for this: 

[https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.16](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.16 )

[Avoid poToken experiment player responses](https://github.com/yt-dlp/yt-dlp/commit/8b8b442cb005a8d85315f301615f83fb736b967a)

Suggest updating Lidatube to the latest YT-DLP to fix this issue.

**Comment by TheWicklowWolf** [comment]
There is already a nightly GitHub action that checks for a new version of yt-dlp. If a new version is found, it updates the requirements and builds a new image with the latest tag. 

It is recommended to use Watchtower for automatic updates, or you can manually update by running `docker pull && docker compose up -d`
