### ISSUE TITLE
[Feature Requests] Download folder location, CA cert store, Other-than-docker installation, all local js, reverse proxy sub dir

### ISSUE THREAD

**Issue by tunloop** [TheWicklowWolf/LidaTube#27]
I just started using this to pull in a bunch of singles and niche artists that I couldn't automatically pull through normal indexers.
I really like this project, and would love to see a couple more features:

- Allow specifying the download destination directory, file format (Dir and file naming scheme), and cache directories in the settings file.
- Currently, python web requests are using the python ca store in `/usr/lib` or `/usr/local/lib`. I don't know if this could be changed by you or if its the backend libraries, but it would be nice to have python use the system CA certificate stores instead of its own (`/etc/ssl/certs/ca-certificates.crt` on Debian).
- Some instructions and official template files for a non-docker installation. Being a python script with some javascript, this seems like a little overkill for a whole container (although people should have a choice), I would love to see some basic instructions and maybe a sample systemd service file for installation manually.
- Support for putting the web interface on a specific url path, like https://192.168.1.1/lidatube (and specifying it in the settings file)
- Being this is mainly directed at self hosters, I think it would be great to have all javascript served from the first party domain only, eliminating the need for the client browser to pull libraries from cloudflare and jsdelivr CDNs.

I appreciate all the work you have done here and hope this isn't too much to ask! :)

**Comment by TheWicklowWolf** [comment]
> * Allow specifying the download destination directory, file format (Dir and file naming scheme), and cache directories in the settings file.

You can indeed specify the download destination directory through the mount options. If you prefer not to use the Lidarr root folder, you can select a different folder and handle the import from there. This gives you flexibility in managing where your downloads are stored.


> * Currently, python web requests are using the python ca store in `/usr/lib` or `/usr/local/lib`. I don't know if this could be changed by you or if its the backend libraries, but it would be nice to have python use the system CA certificate stores instead of its own (`/etc/ssl/certs/ca-certificates.crt` on Debian).

This behavior is a result of the standard implementation of Python’s request libraries.



> * Some instructions and official template files for a non-docker installation. Being a python script with some javascript, this seems like a little overkill for a whole container (although people should have a choice), I would love to see some basic instructions and maybe a sample systemd service file for installation manually.

The idea of a container is the simplicity of installation, if you want to run it another way you can just copy the files.



> * Support for putting the web interface on a specific url path, like https://192.168.1.1/lidatube (and specifying it in the settings file)

I don't have a use case for this.



> * Being this is mainly directed at self hosters, I think it would be great to have all javascript served from the first party domain only, eliminating the need for the client browser to pull libraries from cloudflare and jsdelivr CDNs.

I can't see any major issue with pulling from cdn.jsdelivr.net or cdnjs.cloudflare.com

**Comment by TheWicklowWolf** [comment]
Thanks for your interest.

Unfortunately, I’m not interested in adding these features as I don't see a significant benefit. However, you’re welcome to fork the project and customize it to fit your needs.

Best of luck with it.
