### ISSUE TITLE
Error downloading any track

### ISSUE THREAD

**Issue by iris1801** [TheWicklowWolf/LidaTube#28]
There's some issue with the player that lidatube uses to get the tracks. Since this morning it spits out errors like these:

```
Starting Download of: Snowman (Slowed Down)
lidatube  | [youtube] Extracting URL: https://www.youtube.com/watch?v=OK9GdOBfq54
lidatube  | [youtube] OK9GdOBfq54: Downloading webpage
lidatube  | [youtube] OK9GdOBfq54: Downloading ios player API JSON
lidatube  | ERROR: [youtube] OK9GdOBfq54: The following content is not available on this app.. Watch on the latest version of YouTube.
lidatube  | Error downloading song: https://www.youtube.com/watch?v=OK9GdOBfq54. Error message: ERROR: [youtube] OK9GdOBfq54: The following content is not available on this app.. Watch on the latest version of YouTube.
```

Mayebe some issue with the yt-dlp version used in the container?

Thank you in advance for the great job done since now

**Comment by Wicksy24** [comment]
also having this issue, just found LidaTube, excited to get it working.

**Comment by Jeraimee** [comment]
There's some updates needed to the container due to YT changes.

**Comment by Jeraimee** [comment]
Just forked to do a pull request and you beat me to it. a54022c fixes it.

**Comment by iris1801** [comment]
Still not pushed to the Docker container unfortunately

**Comment by TheWicklowWolf** [comment]
There is an automatic GitHub Action that checks for the latest stable version of yt-dlp. If a new version is available, it updates the requirements, builds the new image, and pushes it to Docker Hub.

If you are using Watchtower, it should handle updates automatically. Otherwise, you will need to update using  `docker pull && docker compose up -d`

**Comment by TheWicklowWolf** [comment]
If you need to update sooner, you can manually update yt-dlp directly within the LidaTube container.

**To update manually:**
- Get into the LidaTube Docker container:
```sh
docker exec -it lidatube /bin/sh
```
- Update yt-dlp to the latest **stable** version:
```sh
pip install --upgrade yt-dlp
```
- Or to update to **nightly** version:
```sh
python3 -m pip install -U --pre "yt-dlp[default]"
```

**Comment by iris1801** [comment]
Updated the container, now the yt-dlp version is 2024.8.1, but same errors spitted out by the console when trying to download tracks.

Here's the output of pip install `--upgrade yt-dlp in the container shell:
`
```
/lidatube $ pip install --upgrade yt-dlp
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: yt-dlp in /usr/local/lib/python3.12/site-packages (2024.8.1)
Requirement already satisfied: brotli in /usr/local/lib/python3.12/site-packages (from yt-dlp) (1.1.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/site-packages (from yt-dlp) (2024.7.4)
Requirement already satisfied: mutagen in /usr/local/lib/python3.12/site-packages (from yt-dlp) (1.47.0)
Requirement already satisfied: pycryptodomex in /usr/local/lib/python3.12/site-packages (from yt-dlp) (3.20.0)
Requirement already satisfied: requests<3,>=2.32.2 in /usr/local/lib/python3.12/site-packages (from yt-dlp) (2.32.3)
Requirement already satisfied: urllib3<3,>=1.26.17 in /usr/local/lib/python3.12/site-packages (from yt-dlp) (2.2.2)
Requirement already satisfied: websockets>=12.0 in /usr/local/lib/python3.12/site-packages (from yt-dlp) (12.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.12/site-packages (from requests<3,>=2.32.2->yt-dlp) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/site-packages (from requests<3,>=2.32.2->yt-dlp) (3.7)
```

and here's the output from the console when trying to download tracks:

```
lidatube  | Starting Download of: State Of Grace (Acoustic)
lidatube  | [youtube] Extracting URL: https://www.youtube.com/watch?v=FwzwOMIN1vM
lidatube  | [youtube] FwzwOMIN1vM: Downloading webpage
lidatube  | [youtube] FwzwOMIN1vM: Downloading ios player API JSON
lidatube  | [youtube] FwzwOMIN1vM: Downloading tv player API JSON
lidatube  | ERROR: [youtube] FwzwOMIN1vM: The following content is not available on this app.. Watch on the latest version of YouTube.
lidatube  | Error downloading song: https://www.youtube.com/watch?v=FwzwOMIN1vM. Error message: ERROR: [youtube] FwzwOMIN1vM: The following content is not available on this app.. Watch on the latest version of YouTube.

```

**Comment by TheWicklowWolf** [comment]
I can't replicate this issue, and since LidaTube relies on yt-dlp, there's not much I can do about it anyway. You'll have to wait until a new version of yt-dlp is released and then update accordingly.

In the meantime, you could try updating to the **nightly** version of yt-dlp:
```sh
docker exec -it lidatube /bin/sh
python3 -m pip install -U --pre "yt-dlp[default]"
```

**Comment by TheWicklowWolf** [comment]
Last Note: You probably have to restart the LidaTube container after manually updating the yt-dlp version in the container.

**Comment by iris1801** [comment]
Even with the nightly yt-dlp same error.
Yup i rebooted on the stable yt-dlp install and on the nightly.
 i'll just wait, thank you for your support!
