### ISSUE TITLE
Unable to download anything

### ISSUE THREAD

**Issue by trekkerofficial** [TheWicklowWolf/LidaTube#29]
For everything it attempts to download, I receive the following error message -
"Valid link count of 0 for: XXX
Downloading Finished"

i have almost 17K Missing records in Lidarr, and I can't get any of them to successfully download through Lidatube

**Comment by TheWicklowWolf** [comment]
What hardware are you using? And what is your exact setup?

From the message, it seems like it's not finding any links. I'm not sure what's causing that. Maybe try running one (with the lowest track count) and check the logs from start to finish. This might help narrow down the issue.

I can't replicate it, so you might need to clone or copy the files and run them locally on your machine. This way, you can step through the code to pinpoint where the issue occurs.

**Comment by DalaraAFL** [comment]
Hey just so you know, i ran into a similar issue with my large lidarr library.

Essentially lidatube seems to do 2 passes when ingesting, first pulling all the albums into it, then another pass getting the tracks. If you start downloading while it says 0/0 (still enumerating albums) then i was consistently getting "Valid link count of 0 for :xxx Downloading finished" However if i waited for it to parse all the albums, and cycle back to filling out the track count, i would get like 0/32 or something for the albums, then pressing download didnt have issues for me

**Comment by trekkerofficial** [comment]
> Hey just so you know, i ran into a similar issue with my large lidarr library.
> 
> Essentially lidatube seems to do 2 passes when ingesting, first pulling all the albums into it, then another pass getting the tracks. If you start downloading while it says 0/0 (still enumerating albums) then i was consistently getting "Valid link count of 0 for :xxx Downloading finished" However if i waited for it to parse all the albums, and cycle back to filling out the track count, i would get like 0/32 or something for the albums, then pressing download didnt have issues for me

This was the fix. I had to wait over 3 days for it to get through both passes, it is now successfully processing

**Comment by TheWicklowWolf** [comment]
> > Hey just so you know, i ran into a similar issue with my large lidarr library.
> > Essentially lidatube seems to do 2 passes when ingesting, first pulling all the albums into it, then another pass getting the tracks. If you start downloading while it says 0/0 (still enumerating albums) then i was consistently getting "Valid link count of 0 for :xxx Downloading finished" However if i waited for it to parse all the albums, and cycle back to filling out the track count, i would get like 0/32 or something for the albums, then pressing download didnt have issues for me
> 
> This was the fix. I had to wait over 3 days for it to get through both passes, it is now successfully processing
> 
> for reference I had about 16k missing tracks to process over that time frame

The approach is to first gather all the missing albums and then go back for the track listings, so increasing `thread_count` should also help speed this up.

I didn’t anticipate someone using it to complete an entire library all at once, especially with such a large number of tracks—it was more intended for filling in gaps. 

It’s not mentioned in the README, but I’d recommend unmonitoring items in your library and then focusing on smaller portions at a time. This way, it can process sections more smoothly, and make the import process easier as well.
