### ISSUE TITLE
Permission Issue: PUID, PGID, UMASK

### ISSUE THREAD

**Issue by Investigamer** [TheWicklowWolf/LidaTube#32]
Howdy, I'm having issues trying to reconcile file permissions between Lidarr and Lidatube. It seems like the primary issue is that providing a PUID or PGID variable doesn't actually change the user:group assignment for Lidatube, instead it always runs as 1000:1000. Since Lidarr (and linuxserver containers broadly) typically use 99:100 this makes things kind of awkward if you want to perform file moves from lidatube volume -> lidarr (copying works, but in my case moving is preferable). 

The UMASK variable also doesn't seem to be used or apply to Lidatube, as directories created during initial startup seem to have the same permissions regardless of what is provided (which are in conflict with Lidarr). An awkward side effect of this is the config settings file isn't generated either if you map a config directory that hasn't already been created, the permissions of the config folder Lidatube creates doesn't allow lidatube to write the settings file lol.

**Comment by TheWicklowWolf** [comment]
Lidatube runs as 1000:1000 by default and doesn't support PUID/PGID changes.
To fix permission issues, simply align your setup with Lidatube's default user/group settings.

**Comment by TheWicklowWolf** [comment]
Fixed in latest release
