### ISSUE TITLE
Cant get Lidarr auto import working

### ISSUE THREAD

**Issue by elliottmarter** [TheWicklowWolf/LidaTube#33]
I appreciate I might be doing something wrong here, so any assistance would be great.

I have LidaTube setup to place any downloads directly in to /media/music

/media/music is the same root folder for Lidarr

WIthin this is the usual /artist/album/song layout

What is currently happening is any missing songs LidaTube grabs are placed in the artist correct folder.

Lidarr sees these OK and marks the file as "green" - However lidarr does not trigger a rename of the files.

Also since LidaTube names the album folder different I end up with songs split across 2 folders

media/music/artist_name/exisiting_album_folder (these were previously grabbed by another download client)
media/music/artist_name/LidaTube_album_folder (contains all the songs LidaTube grabbed)

I _think_ this is because LidaTube is has set owner to my user and permissions to drwxr-xr-x

Wheras Lidarr has all my folders set to "nobody" as the owner and permissions as drwxrwxrwx

In Lidarr if I select the album and click "Preview Rename" nothing happens

However if I manually change the folder Lidatube has grabbed to "Nobody" as the owner and permissions to drwxrwxrwx and then do "Rename" via Lidarr, it works perfectly and the 2 folders merge together.

Am I doing something wrong here?

How can I make LidaTube set the correct permissions on its downloads so Lidarr can then rename and merge etc.

**Comment by elliottmarter** [comment]
Apologies, I am just reading through the closed issues now - I suspect I might need to change Lidarr back to the default naming setup?

and/or change folder perms to match...dont worry for now, Ill see if I can figure it out to work better!

**Comment by Kapoowe-ai** [comment]
If you are still stuck on this, or if someone else comes across this issue and needs help, along with putting lidatube's download folder in you music library folder, assign it the same PUID and PGID. This gives them the same user and group, allowing for no permission issues.
