### ISSUE TITLE
Config file or .env ? Possible to add an example?

### ISSUE THREAD

**Issue by semiligneous** [TheWicklowWolf/LidaTube#34]
Thanks for this project!

In the example docker-compose you mount a config folder:

- /path/to/config:/lidatube/config

What is this intended to contain? What file/s do you add here to  be picked up?

I see you can add environment variables for settings, are these intended to be added to a file within the above mentioned config directory, or as a .env file (with a corresponding lone added to docker-compose.yml to specify the env file)?

An example of best practise for using the variables would be greatly appreciated!

Cheers

**Comment by TheWicklowWolf** [comment]
You can set environment variables directly in the Docker Compose file. 
Any settings saved during runtime are stored in a file within the config folder.

**Note:** Environment variables defined in the Docker Compose file override settings in the configuration file upon the next restart. This means that if an environment variable is set, any runtime changes to that setting will not persist after a restart.
