### ISSUE TITLE
thank you for this tool

### ISSUE THREAD

**Issue by d4nm0** [TheWicklowWolf/LidaTube#35]
i have a problem, sometimes the first track downloads with undefined inside and ocup my plex doesn't map it with the album.
and another thing: after downloading the labum from your lidarr application, it doesn't recognize it, so I don't know if it's been downloaded correctly. Is there a setup to be done so that album downloads are located in a folder bearing the name of the album? and not directly in the folder bearing the name of the artist?

otherwise thank you because it works great for music that is not found with the indexer.

**Comment by TheWicklowWolf** [comment]
You might need to remove the problematic folder, scan your Plex library, then add it back and rescan to fix the mismatch in Plex.

You may also need to manually match the album in Lidarr, and use the rename and retag functions to get the correct file structure and metadata.

See https://thewicklowwolf.github.io/music-stack/

Best of luck with it.
