### ISSUE TITLE
A couple RFEs for new options

### ISSUE THREAD

**Issue by geolaw** [TheWicklowWolf/LidaTube#5]
Posted on your reddit thread where you announced these as well, but posting here as well.

2 improvements I would like to see -

1. an option to search the lidarr library for a certain artist/album, instead of just "get missing list"

2. On the download side, be able to just select certain tracks to download. I have some albums that have 1 or 2 missing tracks and using lidatube to backfill just those tracks would be great :)

**Comment by TheWicklowWolf** [comment]
Thanks for sharing your suggestions.

While the first point is not unreasonable, it falls outside the current scope of this project.
Regarding your second point, the focus is primarily on retrieving missing albums, but specific tracks selection may be looked at in future.

Feel free to fork the project and incorporate any features you need, or even submit a pull request with your suggestions.
