### ISSUE TITLE
Clean up empty directories

### ISSUE THREAD

**Issue by jeremehancock** [TheWicklowWolf/LidaTube#9]
It would be nice if LidaTube would remove any empty directories from the LidaTube Download Directory. Either on a schedule and/or by adding a button to the `yt_dlp` side of the UI to "Clean Up".

After I import the files into Lidarr I have to manually clean this up. Not a big deal, and I have partially automated it with a Node-Red flow, but it would be nice to have it in the same UI.

This project is great btw!!!

**Comment by TheWicklowWolf** [comment]
Out of scope as LidaTube (downloads folder) can be mapped directly into Lidarr/music folder. 
Seems like you have a way to do it already anyway.

**Comment by jeremehancock** [comment]
> Out of scope as LidaTube (downloads folder) can be mapped directly into Lidarr/music folder. Seems like you have a way to do it already anyway.

That makes sense.
